"""empty message

Revision ID: e47215d95a7a
Revises: 
Create Date: 2020-04-03 16:28:24.534176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e47215d95a7a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('country_cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(length=20), nullable=True),
    sa.Column('url_country', sa.String(length=50), nullable=True),
    sa.Column('total_cases', sa.String(length=20), nullable=True),
    sa.Column('new_cases', sa.String(length=20), nullable=True),
    sa.Column('deaths_cases', sa.String(length=20), nullable=True),
    sa.Column('new_deaths', sa.String(length=20), nullable=True),
    sa.Column('total_recovered', sa.String(length=20), nullable=True),
    sa.Column('active_cases', sa.String(length=20), nullable=True),
    sa.Column('serious_critical', sa.String(length=20), nullable=True),
    sa.Column('date_data', sa.String(length=20), nullable=True),
    sa.Column('hour_data', sa.String(length=5), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('generals_datas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('total_cases', sa.String(length=20), nullable=True),
    sa.Column('total_deaths', sa.String(length=20), nullable=True),
    sa.Column('total_recovered', sa.String(length=20), nullable=True),
    sa.Column('date_data', sa.String(length=20), nullable=True),
    sa.Column('hour_data', sa.String(length=5), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('generals_datas')
    op.drop_table('country_cases')
    # ### end Alembic commands ###
